### PR TITLE
Ensure REPL program library is in libl during execution

### PR DESCRIPTION
**Pull request by martintosney**

### CODE REVIEW

**Review by tom-writes-code — APPROVED** [review]
FYI, I'm completely fine with you just merging without review. I only did one before to see what the gh workflow looked like :)

**Comment by martintosney** [comment]
But I need someone to check my work 😜

**Comment by tom-writes-code** [comment]
I'll endeavour to find a way to turn on notifications properly, I keep missing the updates, which makes me feel even worse for not doing reviews

**Comment by martintosney** [comment]
No worries! No rush, after all

**Pull request merged**
