### PR TITLE
Update build rules for Bob v2.3.5

### PR DESCRIPTION
**Pull request by martintosney**
As per title.

The major benefit of this is that we now get feedback on whether the build worked! 🎉 

image

### CODE REVIEW

**Comment by tom-writes-code** [comment]
Just as a little thing that might be worth keeping in mind, this means that if your default locale is `latin-1`, it will now stop working, spitting out an error message like this:
image
The character encoding it references is the check mark.

I've changed my locale with the following, which I'll write down in case I need to do it again and forget.
```
export LANG=en_GB.utf8
export LC_ALL=EN_GB
locale
```

My original encoding looked like this - which I guess isn't UTF-8 compliant.:
```
LANG=
LC_COLLATE="C"
LC_CTYPE="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_MESSAGES="C"
LC_ALL=
```

**Comment by martintosney** [comment]
I was already setting `LC_ALL` the same way in my `.bashrc`, so hadn't realised this would be a requirement.

I think the Bob project could probably do with checking whether the terminal supports these tick and cross characters before including them in the log. It already does this when seeing if the terminal supports coloured output. But for now, at least, I've configured the SSHD on our system to set `LANG` and `LC_ALL` to appropriate values.

**Comment by martintosney** [comment]
This is due to be fixed in the next release of Bob:

https://github.com/IBM/ibmi-bob/issues/86

**Comment by martintosney** [comment]
The Bob project has released a new version which addresses the locale problems.

Are you happy for this to be merged, @tom-writes-code?

**Pull request merged**
